Objetivo 0
smallPingu/antiTarjetas pull request #1
Opened 2023-09-15 12:38 UTC by smallPingu

2023-09-16 08:00 UTC, JJ commented
Tienes que poner la lista de comprobación y seguirla explícitamente. Cuando lo hagas, solicita revisión o bien mencióname en un comentario.

2023-09-16 11:23 UTC, smallPingu commented
@JJ

2023-09-16 11:27 UTC, JJ commented
> **¿Se trata de un problema real del que se tenga conocimiento personal?** Sí, vivo en una residencia donde sus llaves son tarjetas electrónicas y me dieron esta idea. Además, un hotel que he acudido este verano tenía la funcionalidad de abrir las puertas con una página web.
> 
> **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?** Sí, al tener que abrir una puerta mediante una página web, además de varias más funciones posibles de la aplicación del hotel que pueden ser guardados en la nube.
> 
> **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?** La comprobación de geolocalización por parte del número de teléfono y de la ubicación del móvil cuando se usa la página web requiere una lógica de negocio. Además, cuando se implementen las diferentes funciones de la aplicación como puede ser el check-in_check-out automático, estos requerirán lógica de negocio, dependiendo de la complejidad de la función.
> 
> **¿Se ha incluido la configuración del repositorio y se ha enlazado desde el README?** Sí, configuración de la llave SSH y la configuración de email y usuario en el pc local.
> 
> **¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?** El usuario sólo deberá proporcionar datos de contacto al hotel, de ahí se sacaran los datos necesarios.
> 
> **¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?**
> 
> ![illustration-of-a-oool-yellow-smiley-with-sunglasses-picture-id513921039-4083998218](https://user-images.githubusercontent.com/134606360/268445178-594ef044-c5ce-4fb4-903a-dad72c264c2b.jpeg)

Sin duda, esta es la respuesta correcta.

2023-09-16 11:32 UTC, JJ requested changes
¿Este problema te lo validaron en el juego de rol?

Repetí varias veces en clase que no serían válidos problemas ligados a ningún tipo de dispositivo físico. 

Tampoco tiene ninguna lógica de negocio aparente (más allá de almacenar los códigos), y tiene otra serie de errores: sólo has modificado una parte del README en el PR (lo que hace difícil evaluarlo) y algunos errores menores (modesto hotel de 500 habitaciones, hotel suizo en uno y sueco en otro).
El problema principal, de todas formas, es que no describes un problema, sino una solución informática a un problema que no tengo claro que exista.
También falta que incluyas los elementos de configuración que se te piden en el guión. Por favor, corrige todo esto 
En todo caso, el "individuo con traje y corbata" no deja de recordarme a este:
![Monoraaaaillll!](https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2017/02/simpson-4x12.jpg?tf=3840x)

2023-09-18 14:37 UTC, smallPingu reviewed
Nueva idea de problema

2023-09-18 14:40 UTC, smallPingu commented
@JJ Actualizado, pero me sale un mensaje que dice "This branch has conflicts that must be resolved"

2023-09-18 15:32 UTC, JJ commented
Pues tendrás que resolverlo, efectivamente. Si no no sirve de nada que lo apruebe o no, porque no podrás fusionarlo.
¿Has modificado la rama Objetivo-0, o la main?

2023-09-18 15:44 UTC, smallPingu commented
@JJ He modificado las líneas que mostraban error (eran líneas que se supone que estaban repetidas entre el main y el objetivo 0, no lo entendí muy bien) y ya no da error. Modifiqué en un principio la rama Objetivo-0.

2023-09-18 16:03 UTC, JJ requested changes
Como vimos en el juego de rol, deberías ser capaz de describir el problema para que otra persona empiece a trabajar en él. Adicionalmente, insisto en la necesidad de que haya un conocimiento personal del problema. Descripciones vagas o demasiado generales en general evidencian la "creación" de un problema para entregarlo en este objetivo en vez de la genuina descripción de un problema del que se tenga conocimiento y voluntad de solución.

2023-09-18 16:03 UTC, JJ commented on README.md
> +Tengo que separar mis proyectos para que no se mezclen entre ellos, acordarme de todos mis contactos, (_los cuales además están en constante cambio_), seguir las deadlines, llevar a cabo análisis sob
De los [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md#con-respecto-a-los-problemas-enviados):

> Descripciones de problemas difíciles de comprender, lo que normalmente es consecuencia de una baja empatía; no te has colocado en la piel del cliente para entender qué quiere hacer y qué problema tiene.

¿El problema es que los "proyectos" están "mezclados"?

2023-09-21 11:32 UTC, JJ commented
Cuando esté listo pide explícitamente la revisión.

2023-09-22 09:22 UTC, smallPingu commented
@JJ Cambio de idea y lista de comprobación reescrita.

2023-09-25 11:49 UTC, JJ requested changes
Como lo hablamos en clase, te dejo constancia aquí para que intentes reorientar el problema a extraer información que sea capaz de describir el estado de ánimo adecuado para cada película a partir de su descripción en una base de datos.

2023-09-25 11:49 UTC, JJ commented on README.md
> +Netflix, Hulu y demás plataformas de streaming pueden recomendarte peliculas y series según lo que consumas en la plataforma, aplicando un algoritmo de recomendación basado en lo que visualizas, pero
Como hablamos en clase, "generar listas" no sería un problema adecuado, sobre todo si no tienes bien claro qué es lo que realmente vas a hacer ni qué algoritmo vas  a aplicar.

2023-09-25 11:49 UTC, JJ commented on README.md
> +Tener una aplicación que genera una lista con series y películas que estén adecuados a tus gustos y como te sientes en el momento, analizando cuales son las series y películas que te gustan (encuesta
En ningún momento hemos dicho que incluyáis una solución salvo que sea imprescindible para entender que la lógica de negocio no es trivial

2023-09-25 14:33 UTC, smallPingu commented
Recibido, gracias por recordar. 
Me pondré cuanto antes en la alteración del problema.

2023-09-27 21:57 UTC, smallPingu commented
@JJ

2023-09-28 10:26 UTC, JJ requested changes
Gracias por modificarlo, pero todavía hace falta algo más de precisión en la descripción del problema. Según [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio):

> aplicaciones que tengan una dependencia externa fuerte (por ejemplo, que recojan datos de un API externo, que pidan una gran cantidad de datos al usuario o que simplemente integren una biblioteca externa para llevar a cabo una operación sobre datos también externos) tampoco van a ser buenos proyectos, porque sus pruebas van a ser complicadas y no van a incluir ningún tipo de modelo. 

Si *el problema* es procesar los datos de la Junta porque estén en un formato poco estructurado, por favor, descríbelo así. Si se trata de algoritmos de predicción, desgraciadamente, quedan fuera del ámbito de la asignatura por su complicación.

2023-09-28 10:26 UTC, JJ commented on README.md
> +Gracias a los datos aportados por la Junta de Andalucía, podemos analizar el estado del tiempo presente, pasado y futuro de un entorno para predecir si la zona por la que quieres usar la bicicleta es
Tendrás que concretar un poco más qué datos quieres decir. No sé si la Junta tiene datos meteorólogicos, y más con la precisión que puede requerir una ruta en bicicleta.

2023-09-29 10:25 UTC, smallPingu commented on README.md
> +Gracias a los datos aportados por la Junta de Andalucía, podemos analizar el estado del tiempo presente, pasado y futuro de un entorno para predecir si la zona por la que quieres usar la bicicleta es
Los datos son agroclimáticos, y son usados para la agricultura. Al haber rutas dedicadas para vehículos de agricultura, los ciclistas pueden circular por estos caminos. Dependiendo de las condiciones meteorológicas, humedad y demás factores, estos terrenos serán más o menos cómodos para un ciclista. Tales datos están en un formato csv, los cuales son estructurados.

Además, las condiciones meteorológicas pueden ser un factor determinante para los ciclistas (esta página tiene varias opciones https://www.aemet.es/es/datos_abiertos)

El problema es procesar los diferentes datos para poder informar al ciclista que zonas están recomendadas para circular, no procesar el camino a tales zonas (parte de la diversión del ciclismo es explorar). Como mencioné, los datos agroclimáticos están estructurados, pero la API de las condiciones meteorológicas se debe pedir una key para poder usarla https://opendata.aemet.es/centrodedescargas/inicio, así que no sé si está estructurada o semi-estructurada.

Ahora en clase lo comentamos.

2023-09-29 11:48 UTC, smallPingu commented
@JJ

2023-09-29 12:22 UTC, JJ approved these changes
👍

2023-10-06 11:02 UTC, merged