[IV-23-24] Objetivo 1
smallPingu/antiTarjetas pull request #8
Opened 2023-10-06 12:18 UTC by smallPingu

Hice un commit que no es relevante ("Ni caso")

2023-10-09 19:21 UTC, pluque01 requested changes
Voy a decirte algunas cosas que tienes que hacer antes de superar el objetivo:

* Debes crear ficheros separados para los milestones y las historias de usuario (te recomiendo con la extensión de Markdown)
* Las historias de usuario deben estar escritas en primera persona. Al fin y al cabo es el cliente el que está expresando sus deseos y necesidades
* Los milestones además de ser asignados a una historia de usuario deben describir un producto y qué lo hace válido

Puedes echar un vistazo a otra gente que ya ha superado el objetivo, creo que te aclarará un poco más los requisitos del mismo. ¡Mucho ánimo!

2023-10-10 18:01 UTC, JJ commented
Quizás @moshidev @josemponce pueden echarle un vistazo

2023-10-11 05:57 UTC, moshidev commented
Dependiendo de las historias de usuario que se quieran abordar creo que también sería conveniente añadir información o al menos dónde se puede consultar información acerca del dominio del problema, para que el compañero que vaya a trabajar en el proyecto pueda entender mejor cosas específicas del senderismo que son conocidas por quienes practican el deporte, pero no necesariamente por quienes no.

2023-10-13 14:38 UTC, smallPingu commented
@pluque01 @moshidev  ¿Qué tal lo veis?

2023-10-13 14:54 UTC, moshidev commented
Los Milestones tienen que expresaste como producto (¿qué vamos a entregar? ¿qué lo hace válido?)

Por otra parte, sobre una revisión puedes contestar a los comentarios que te han hecho. Cuando el comentario está resuelto puedes escribir un último comentario explicando en qué commit está resuelto y darle al botón de resolve.

2023-10-14 17:00 UTC, pluque01 commented
Básicamente lo que te ha dicho @moshidev acerca de los milestones. Además por lo que veo tu lógica de negocio del milestone 0 se basa simplemente en leer y mostrar datos. Creo que te va a hacer falta algo menos trivial que eso para superar el objetivo.

Y no te desanimes, vas en la buena dirección :))

2023-10-18 14:47 UTC, smallPingu commented
> Básicamente lo que te ha dicho @moshidev acerca de los milestones. Además por lo que veo tu lógica de negocio del milestone 0 se basa simplemente en leer y mostrar datos. Creo que te va a hacer falta algo menos trivial que eso para superar el objetivo.
> 
> Y no te desanimes, vas en la buena dirección :))

Escribí los milestones con una mayor exactitud para expresar con más certeza el porqué de tales, dando así una dirección más definida para futuros objetivos. @pluque01  @moshidev

2023-10-19 06:46 UTC, pluque01 commented on docs/MileStones
> +		Aplicación que recopile y encuentre archivos de varias páginas web, sabiendo que cada una de ellas tiene una forma distinta de organizarlos.
Creo que te sigue faltando explicar qué hace valido al producto que vas a entregar. Por ejemplo, el pasar ciertos tests o la aprovación del product owner.

2023-10-19 06:47 UTC, pluque01 requested changes

2023-10-19 06:47 UTC, pluque01 commented on docs/MileStones
> +		Aplicación que recopile y encuentre archivos de varias páginas web, sabiendo que cada una de ellas tiene una forma distinta de organizarlos.
Creo que te sigue faltando explicar qué hace valido al producto que vas a entregar. Por ejemplo, el pasar ciertos tests o la aprovación del product owner.

2023-10-20 16:06 UTC, smallPingu commented on docs/MileStones
> +		Aplicación que recopile y encuentre archivos de varias páginas web, sabiendo que cada una de ellas tiene una forma distinta de organizarlos.
He alterado el documento _doc/Milestones_ y las propias **milestones** para que se pueda entender con más exactitud el propósito y el PMV del Milestone0. Además se extiende sobre el Milestone 0 el Milestone 1, marcando así una dirección en la que podemos trabajar con un destino en mente para nuestro proyecto.

En resumen, creo que ahora se entiende mejor el producto y con ello, lo que le hace válido. No quiero poner "El producto es ... y es válido por ...", pero que se entienda con la descripción del mismo.

Porfavor, corregidme si me equivoco en mi razonamiento @moshidev @pluque01.

2023-10-21 10:31 UTC, moshidev reviewed
Una página web es algo muy complejo, antes de centrarnos en la tecnología en concreto queremos analizar el problema para hacer un modelo. Los milestones están definidos por una Producto _Mínimamente_ Viable. Queremos fallar cuanto antes e iterar mucho para poder encontrar el camino correcto lo antes posible.

Por otra parte, ¿qué se busca? ¿_scrappear_?

2023-10-31 06:46 UTC, JJ commented
¿Está esto listo para que lo revise? ¿Aprobado?

2023-10-31 07:17 UTC, moshidev commented
Le falta un poco para estar aprobado.

2023-10-31 16:35 UTC, smallPingu commented
> Le falta un poco para estar aprobado.

He modificado los últimos detalles que me mencionaste anteriormente. Comunícame si me falta algún otro o si ya está listo para revisar.

2023-11-02 19:11 UTC, JJ commented
Por favor, @smallPingu, haz un pequeño esfuerzo para sacar esto. Siguiendo las indicaciones de los compañeros puedes sacarlo, y también @alvarosanpal95 puede revisarlo. Así cuando lo superes podéis trabajar cada uno en el repo del otro, que sois los últimos que habéis entregado y seguís sin objetivo 2 asignado.

2023-11-04 13:30 UTC, smallPingu commented
Me pondré cuanto antes a revisar las últimas indicaciones, he tenido 
unas semanitas ajetreadas. Gracias por el recordatorio.

El 2023-11-02 20:11, Juan Julián Merelo Guervós escribió:
> Por favor, @smallPingu, haz un pequeño esfuerzo para sacar esto. 
> Siguiendo las indicaciones de los compañeros puedes sacarlo, y también 
> @alvarosanpal95 puede revisarlo. Así cuando lo superes podéis trabajar 
> cada uno en el repo del otro, que sois los últimos que habéis entregado 
> y seguís sin objetivo 2 asignado.

2023-11-04 16:04 UTC, smallPingu commented
@pluque01 @AlvaroSanPal95 @moshidev 
Editado los detalles, echad un vistazo cuando podáis.

2023-11-06 17:27 UTC, AlvaroSanPal95 commented
Buenas tardes @smallPingu;

He estado repasando el contenido actual de tu rama Objetivo-1, y también lo que han comentado @pluque01 y @moshidev.

Básicamente es lo mismo que te han estado diciendo ellos, pero te doy algunas recomendaciones por si ayuda otra perspectiva:

Respecto a las historias de usuario, intentaría juntar todo lo que hay en ellas, de forma que no te refieras a Beneficios y Deseo, sino que sea el propio usuario en primera persona quien cuente también esa parte. Por otro lado no especificaría el producto en las HU, ya que no deben expresar nada de la resolución, sino solo problemas/objetivos/deseos.

Respecto a los Milestones, te recomendaría que el primero (Milestone 0) fuese interno, y tratase el modelo del problema en general, de forma que quede más claro el abordaje de los siguientes milestones con dicho modelo general y sus componentes.

Vas por buen camino, tal y como comentaban los compañeros, te recomiendo echarle un vistazo a los proyectos de algunos compañeros que hayan superado este objetivo, para que veas un poco la estructura general y la forma de expresar dichos contenidos

Un saludo!

2023-11-09 09:30 UTC, smallPingu commented
@AlvaroSanPal95 Recibido, gracias al comentario entendí que tenía que hacer para el MileStone0. Cambié lo que vi necesario y el proyecto lo veo preparado para su corrección.

2023-11-09 17:44 UTC, pluque01 approved these changes
Veo que vas en la buena dirección, ya casi lo tienes :))

2023-11-09 17:44 UTC, pluque01 commented on docs/MileStones
> +MileStone0:
Este milestone lo veo bien 👍

2023-11-09 17:44 UTC, pluque01 commented on docs/MileStones
> +MileStone1:
Aquí te falta seguir la misma estructura que en el milestone 0. Definir cuál va a ser el entregable y cuando va a ser viable El objetivo supongo que es lo que tienes actualmente aunque igual podrías recortar un poco y dejar lo esencial.

2023-11-09 18:46 UTC, smallPingu commented on docs/MileStones
> +MileStone1:
Recibido y corregido :)

2023-11-10 15:42 UTC, smallPingu commented
@JJ Creo que ya está completado este objetivo. ¿Podría revisarlo para pasar al siguiente objetivo cuanto antes? Gracias.

2023-11-10 18:50 UTC, JJ approved these changes
Muchas gracias a @moshidev, @pluque01 y @alvarosanpal95 por la colaboración. No es perfecta. Por ejemplo, me hubiera gustado ver explícitamente la palabra "Historia de usuario" en el documento correspondiente, más que nada para ver que no se confunde con otras cosas. También en la descripción de los milestones hay un poco de *boilerplate* o copia/pega que a veces denota una comprensión superficial de lo que implica cada cosa.
Pero a estas alturas de la película no voy a andar con muchos remilgos. Sí sería conveniente ponerse inmediatamente con el objetivo 2 para entregar en las próximas dos semanas. Hago la asignación inmediatamente.

2023-11-10 18:50 UTC, JJ commented on docs/MileStones
> +MileStone0:
Por favor, en el futuro resolved todos los comentarios. Lo podéis hacer directamente desde el menú, y si es un cambio hecho en otro lado, con el commit en el que se ha yecho el cambio.

2023-11-10 18:50 UTC, JJ commented on docs/MileStones
> +	Objetivo: El propósito es llevar a cabo un análisis de las Unidades de Herramienta (HUs) con el fin de identificar y extraer los diversos componentes que componen al problema, y posteriormente codif
HU son Historias de Usuario.

2023-11-10 18:50 UTC, JJ commented on docs/MileStones
> +	Objetivo: Generar una aplicación sencilla que nos permita realizar un scrapping de diversas páginas web, con el fin de extraer información relevante.
scraping lleva una sola p.

2023-11-24 00:25 UTC, merged